### PR TITLE
new website design

### PR DESCRIPTION
**Pull request by qwertyytheartist**
makes the website look better, but doesn't change any real functionality.

### CODE REVIEW

**Comment by Mariocraft987** [comment]
Bro this broke the link system

**Comment by qwertyytheartist** [comment]
> Bro this broke the link system

what do you mean? the website functions a-o-k

**Comment by Mariocraft987** [comment]
I fixed by taking away the "/" in "/favicon.ico" and many other links

**Comment by qwertyytheartist** [comment]
> I fixed by taking away the "/" in "/favicon.ico" and many other links

oh, ok. i didn't realize the icon stopped working, ooops

**Pull request merged**
